"""boilpayment -- root export.

Deliberately narrow (see ../README.md "Root export & name collisions" for the full rationale and
the two real name collisions this avoids). What's here:
  1. The full surface of boilpayment_core (types, Policy, Clock/IdGen, period/money
     helpers, idempotency helpers, in-memory reference implementations, logging) -- this is what
     every other module's function signatures are built from, so it's safe and expected to be
     fully available at the root.
  2. A curated set of the most-used entry points from the five core operation modules
     (lifecycle, credits, refund, usage, webhook), so
     `from boilpayment import upgrade, consume, evaluate, record, receive` covers the
     common path without picking a submodule.

NOT re-exported here -- use the dedicated submodule instead:
  - `.stripe`, `.toss`, `.portone`, `.polar` -- the four provider adapters export several
    same-named functions/types with DIFFERENT shapes (`normalize_failure`,
    `normalize_subscription`, `normalize_refund`, `map_event_type`, `to_normalized_event` collide
    between stripe/polar; `CashReceiptType`, `CashReceiptStatus`, `CashReceipt` collide between
    toss/portone). Bundling any two of them at the root would silently shadow one implementation
    with the other.
  - `.notify`, `.cs`, `.postgres` -- add-on/infra modules, not every project uses them.
  - `.refund`'s own `proration_ratio` (and `days_between`/`apply_rounding`/
    `weighted_avg_unit_price`) -- `proration_ratio` is a REAL collision with core's own
    `proration_ratio` (re-exported via #1 above); refund's copy is available at `.refund` only, so
    `from boilpayment import ...` always gets core's version unambiguously.
  - the rest of `.lifecycle` (`downgrade`/`convert_trial`/`retry_on_version_conflict`/the
    `dunning`, `scheduler`, `period` submodules), `.credits` (`grant_for_period`/
    `rollover_on_renewal`/`clawback`/`expire_due`/`notify_expiring`), `.usage`
    (`close_period`/`flush_outbox`), `.webhook` (`process_pending`/`default_handlers`/http
    helpers/correlation ids) -- deeper wiring, no collisions, just kept off the root to keep it a
    short list. Pull them from their submodule.
"""

from __future__ import annotations

from boilpayment_core import (
    DEFAULT_POLICY,
    ZERO_DECIMAL_CURRENCIES,
    AnnualRefundMethod,
    AppendResult,
    Balance,
    BankReset,
    BaseLogger,
    CancelCredits,
    CancelMode,
    CashReceiptMode,
    CashReceiptRef,
    CashReceiptType,
    Checkout,
    ClawbackShortfall,
    Clock,
    CollectingLogger,
    CollectingNotifier,
    ConsoleLogger,
    ConsumeInput,
    ConsumeOrder,
    ConsumeResult,
    CreateCheckoutInput,
    CsCase,
    CsCaseKind,
    CsCaseStatus,
    Customer,
    CustomerStatus,
    Deps,
    DisputeOnLost,
    DisputeOnOpen,
    DowngradeMode,
    ExpiringBucket,
    FeeBearer,
    FixedClock,
    GrantDuringGrace,
    GrantLagBehavior,
    IdGen,
    InMemoryLedger,
    InMemoryRepo,
    InsufficientBalanceError,
    Interval,
    IntervalChangeMode,
    LedgerEntry,
    LedgerKind,
    LedgerReference,
    LedgerSource,
    LedgerStore,
    Logger,
    LogLevel,
    MemTable,
    Money,
    MonthEndAnchor,
    MultipleSubscriptions,
    NegativeBalance,
    NegativeOffset,
    NewLedgerEntry,
    NoopLogger,
    NoopNotifier,
    NormalizedEvent,
    NormalizedEventType,
    Notification,
    Notifier,
    NotifyType,
    OnFinalFailure,
    OnRecovery,
    Operation,
    OperationStatus,
    OutboxItem,
    Overage,
    OveruseBehavior,
    PauseMode,
    Payment,
    PaymentFailure,
    PaymentKind,
    PaymentKitError,
    PaymentProvider,
    PaymentStatus,
    Period,
    Plan,
    PlanPrice,
    Policy,
    PolicyValidationError,
    Pool,
    PoolMode,
    ProrationDenominator,
    ProviderCapabilities,
    ProviderError,
    ProviderName,
    ProviderRef,
    Refund,
    RefundDecision,
    RefundMethod,
    RefundRounding,
    RefundStatus,
    RegrantMode,
    Repo,
    RevokeShortfall,
    Rollover,
    RunIdempotentResult,
    SequentialIdGen,
    Subscription,
    SubscriptionStatus,
    SystemClock,
    Table,
    TrialAbuseGuard,
    TrialCreditsOnCancel,
    TrialCreditsOnConvert,
    UpgradeCreditDelta,
    UpgradeMode,
    UsageDuringGrace,
    UsageEvent,
    UuidIdGen,
    WebhookEventRecord,
    WebhookEventStatus,
    WebhookSignatureError,
    add_money,
    assert_same_currency,
    days_in_month,
    days_in_period,
    deserialize_cs_case,
    deserialize_ledger_entry,
    deserialize_refund,
    deserialize_subscription,
    elapsed_ratio,
    hash_payload,
    money,
    mul_money_ratio,
    next_period,
    period_containing,
    proration_ratio,
    redact,
    resolve_policy,
    serialize_cs_case,
    serialize_ledger_entry,
    serialize_refund,
    serialize_subscription,
    stable_stringify,
    validate_policy,
)
from boilpayment_credits import consume, topup
from boilpayment_lifecycle import cancel, downgrade, reactivate, upgrade
from boilpayment_refund import evaluate, execute, on_external_refund
from boilpayment_usage import check, record
from boilpayment_webhook import default_handlers, process, receive

__all__ = [
    "DEFAULT_POLICY",
    "ZERO_DECIMAL_CURRENCIES",
    "AnnualRefundMethod",
    "AppendResult",
    "Balance",
    "BankReset",
    "BaseLogger",
    "CancelCredits",
    "CancelMode",
    "CashReceiptMode",
    "CashReceiptRef",
    "CashReceiptType",
    "Checkout",
    "ClawbackShortfall",
    "Clock",
    "CollectingLogger",
    "CollectingNotifier",
    "ConsoleLogger",
    "ConsumeInput",
    "ConsumeOrder",
    "ConsumeResult",
    "CreateCheckoutInput",
    "CsCase",
    "CsCaseKind",
    "CsCaseStatus",
    "Customer",
    "CustomerStatus",
    "Deps",
    "DisputeOnLost",
    "DisputeOnOpen",
    "DowngradeMode",
    "ExpiringBucket",
    "FeeBearer",
    "FixedClock",
    "GrantDuringGrace",
    "GrantLagBehavior",
    "IdGen",
    "InMemoryLedger",
    "InMemoryRepo",
    "InsufficientBalanceError",
    "Interval",
    "IntervalChangeMode",
    "LedgerEntry",
    "LedgerKind",
    "LedgerReference",
    "LedgerSource",
    "LedgerStore",
    "LogLevel",
    "Logger",
    "MemTable",
    "Money",
    "MonthEndAnchor",
    "MultipleSubscriptions",
    "NegativeBalance",
    "NegativeOffset",
    "NewLedgerEntry",
    "NoopLogger",
    "NoopNotifier",
    "NormalizedEvent",
    "NormalizedEventType",
    "Notification",
    "Notifier",
    "NotifyType",
    "OnFinalFailure",
    "OnRecovery",
    "Operation",
    "OperationStatus",
    "OutboxItem",
    "Overage",
    "OveruseBehavior",
    "PauseMode",
    "Payment",
    "PaymentFailure",
    "PaymentKind",
    "PaymentKitError",
    "PaymentProvider",
    "PaymentStatus",
    "Period",
    "Plan",
    "PlanPrice",
    "Policy",
    "PolicyValidationError",
    "Pool",
    "PoolMode",
    "ProrationDenominator",
    "ProviderCapabilities",
    "ProviderError",
    "ProviderName",
    "ProviderRef",
    "Refund",
    "RefundDecision",
    "RefundMethod",
    "RefundRounding",
    "RefundStatus",
    "RegrantMode",
    "Repo",
    "RevokeShortfall",
    "Rollover",
    "RunIdempotentResult",
    "SequentialIdGen",
    "Subscription",
    "SubscriptionStatus",
    "SystemClock",
    "Table",
    "TrialAbuseGuard",
    "TrialCreditsOnCancel",
    "TrialCreditsOnConvert",
    "UpgradeCreditDelta",
    "UpgradeMode",
    "UsageDuringGrace",
    "UsageEvent",
    "UuidIdGen",
    "WebhookEventRecord",
    "WebhookEventStatus",
    "WebhookSignatureError",
    "add_money",
    "assert_same_currency",
    "cancel",
    "check",
    "consume",
    "days_in_month",
    "days_in_period",
    "default_handlers",
    "deserialize_cs_case",
    "deserialize_ledger_entry",
    "deserialize_refund",
    "deserialize_subscription",
    "downgrade",
    "elapsed_ratio",
    "evaluate",
    "execute",
    "hash_payload",
    "money",
    "mul_money_ratio",
    "next_period",
    "on_external_refund",
    "period_containing",
    "process",
    "proration_ratio",
    "reactivate",
    "receive",
    "record",
    "redact",
    "resolve_policy",
    "serialize_cs_case",
    "serialize_ledger_entry",
    "serialize_refund",
    "serialize_subscription",
    "stable_stringify",
    "topup",
    "upgrade",
    "validate_policy",
]
