#!/usr/bin/env bash
# Builds the one PyPI distribution, `boilpayment`, holding every Python module.
#
# The workspace keeps one pyproject per module (packages/*/py, packages/providers/*/py) for
# development and tests. PyPI gets a single distribution instead: the generated code imports only
# the `boilpayment` facade, and creating 14 new PyPI projects at once hits PyPI's
# "Too many new projects created" limit. Import names do not change (boilpayment,
# boilpayment_core, boilpayment_credits, ...), so generated code works either way.
#
# Usage: scripts/build-pypi-bundle.sh <out-dir>
# Builds from the committed HEAD (git archive), never from the working tree.
set -euo pipefail
ROOT="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
OUT="$(mkdir -p "${1:?usage: build-pypi-bundle.sh <out-dir>}" && cd "$1" && pwd)"
WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

git -C "$ROOT" archive --format=tar HEAD | tar -x -C "$WORK"
BUNDLE="$WORK/bundle"
mkdir -p "$BUNDLE/src"

MODULES=(packages/core packages/credits packages/refund packages/usage packages/webhook
  packages/notify packages/schema-postgres packages/lifecycle packages/cs
  packages/providers/stripe packages/providers/toss packages/providers/portone
  packages/providers/polar packages/sdk)
PKGS=()
for m in "${MODULES[@]}"; do
  for d in "$WORK/$m"/py/src/*/; do
    name="$(basename "$d")"
    [[ "$name" == __pycache__ ]] && continue
    cp -R "$d" "$BUNDLE/src/$name"
    PKGS+=("\"src/$name\"")
  done
done

VERSION="$(sed -n 's/^version = "\(.*\)"$/\1/p' "$WORK/packages/sdk/py/pyproject.toml")"
cp "$WORK/packages/sdk/py/README.md" "$BUNDLE/README.md"
cp "$WORK/LICENSE" "$BUNDLE/LICENSE"

# External dependencies = union of every module's non-internal dependencies.
DEPS="$(python3 - "$WORK" <<'PY'
import pathlib, sys, tomllib
root = pathlib.Path(sys.argv[1])
deps = set()
for p in root.glob("packages/**/py/pyproject.toml"):
    for d in tomllib.loads(p.read_text())["project"].get("dependencies", []):
        if not d.startswith("boilpayment"):
            deps.add(d)
print(", ".join(f'"{d}"' for d in sorted(deps)))
PY
)"

cat > "$BUNDLE/pyproject.toml" <<EOF
[project]
name = "boilpayment"
version = "$VERSION"
description = "Payment kit: refunds, dunning, renewals and overage for code generated by npx boilpayment init. Part of Schift's boil series."
readme = "README.md"
license = "MIT"
license-files = ["LICENSE"]
authors = [{ name = "boilpayment contributors" }]
requires-python = ">=3.11"
dependencies = [$DEPS]
classifiers = [
  "Development Status :: 3 - Alpha",
  "Intended Audience :: Developers",
  "Programming Language :: Python :: 3",
  "Topic :: Office/Business :: Financial",
]

[project.urls]
Homepage = "https://github.com/schift-io/boilpayment#readme"
Repository = "https://github.com/schift-io/boilpayment.git"
Issues = "https://github.com/schift-io/boilpayment/issues"

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = [$(IFS=,; echo "${PKGS[*]}")]
EOF

(cd "$BUNDLE" && uv build --out-dir "$OUT")
echo "built boilpayment $VERSION into $OUT"
