// EC:M1 — generated only when the wizard's first answer was "we already have paying customers".
// Writes paykit/backfill.{ts,py} (thin scripts over lifecycle `backfill`), a CSV header the
// developer fills from their old system, and an INTEGRATION.md section. With no existing customers
// none of this is generated, so that output stays byte-identical to before the question existed.
import type { PaykitConfig } from "../config.js";

const NATIVE = ["stripe", "polar"];
const SELF = ["toss", "portone"];

export function hasBackfill(config: PaykitConfig): boolean {
  return config.situation?.existingCustomers === true;
}

/** Columns the developer's export needs, given what they said exists and where. */
export function backfillColumns(config: PaykitConfig): string[] {
  const s = config.situation!;
  const subs = s.has.includes("subscriptions");
  const native = s.providers.some((p) => NATIVE.includes(p));
  const self = s.providers.some((p) => SELF.includes(p));
  const cols = ["customer_id", "email", "provider", "customer_ref"];
  if (subs && native) cols.push("subscription_ref");
  if (subs) cols.push("plan_id");
  if (subs && self) cols.push("billing_key", "period_start", "period_end");
  if (s.has.includes("credits")) cols.push("credits", "credits_expire_at");
  return cols;
}

export function generateBackfillCsv(config: PaykitConfig): string {
  return backfillColumns(config).join(",") + "\n";
}

export function generateBackfillTs(): string {
  return `// Generated by \`boilpayment init\` because you answered that you already have paying customers (EC:M1).
// Brings them into the kit's tables once: customers, their live subscriptions (Stripe/Polar are
// confirmed with the provider; Toss/PortOne use the billing key and paid period from your file) and
// credit balances. Safe to run again: rows already imported are reported as skipped.
//
//   npx tsx paykit/backfill.ts customers.csv
//
// Columns: paykit/backfill.example.csv. DATABASE_URL and provider keys come from the environment.
import { readFileSync } from 'node:fs';
import { pathToFileURL } from 'node:url';
import config from '../paykit.config.json' with { type: 'json' };
import { createPaymentKit, type PaymentKitDeps } from './index.js';
import { SystemClock, UuidIdGen } from 'boilpayment-sdk/core';
import { createPool, PostgresRepo, PostgresLedgerStore } from 'boilpayment-sdk/postgres';
import { backfill, parseBackfillFile, type BackfillReport } from 'boilpayment-sdk/lifecycle';

/** Imports the rows in \`content\` (CSV or JSON) into the repo and ledger in \`deps\`. */
export async function runBackfill(content: string, deps: PaymentKitDeps, opts: { verifySchema?: boolean } = {}): Promise<BackfillReport> {
  const kit = createPaymentKit(config, deps);
  await kit.initialize(opts); // stores the configured plans, so plan_id values resolve
  const { repo, ledger, providers, clock, ids } = kit.deps;
  return backfill({ rows: parseBackfillFile(content), repo, ledger, providers, clock, ids });
}

if (process.argv[1] && import.meta.url === pathToFileURL(process.argv[1]).href) {
  const file = process.argv[2];
  if (!file) {
    console.error('usage: npx tsx paykit/backfill.ts <customers.csv|customers.json>');
    process.exit(2);
  }
  const pool = createPool(process.env.DATABASE_URL!);
  try {
    const report = await runBackfill(readFileSync(file, 'utf8'), {
      env: process.env as unknown as PaymentKitDeps['env'],
      clock: new SystemClock(),
      ids: new UuidIdGen(),
      repo: new PostgresRepo(pool),
      ledger: new PostgresLedgerStore(pool),
    });
    for (const r of report.results) console.log(JSON.stringify(r));
    console.log(JSON.stringify({ ok: report.ok, errors: report.errors }));
    process.exitCode = report.errors ? 1 : 0;
  } finally {
    await pool.end();
  }
}
`;
}

export function generateBackfillPy(): string {
  return `"""Generated by \`boilpayment init\` because you answered that you already have paying customers (EC:M1).

Brings them into the kit's tables once: customers, their live subscriptions (Stripe/Polar are
confirmed with the provider; Toss/PortOne use the billing key and paid period from your file) and
credit balances. Safe to run again: rows already imported are reported as skipped.

    python -m paykit.backfill customers.csv

Columns: paykit/backfill.example.csv. DATABASE_URL and provider keys come from the environment.
"""

from __future__ import annotations

import asyncio
import dataclasses
import json
import os
import sys
from pathlib import Path
from typing import Any

from boilpayment.core import Deps, SystemClock, UuidIdGen
from boilpayment.lifecycle import BackfillInput, BackfillReport, backfill, parse_backfill_file

from .index import create_payment_kit

CONFIG: dict[str, Any] = json.loads((Path(__file__).resolve().parent.parent / "paykit.config.json").read_text())


async def run_backfill(
    content: str,
    deps: Deps,
    env: dict[str, str],
    *,
    verify_schema_first: bool = True,
    providers_override: dict[str, Any] | None = None,
) -> BackfillReport:
    """Imports the rows in \`content\` (CSV or JSON) into the repo and ledger in \`deps\`."""
    kit = create_payment_kit(CONFIG, deps, env, providers_override)
    await kit["initialize"](verify_schema_first=verify_schema_first)  # stores plans so plan_id resolves
    rows = parse_backfill_file(content)
    return await backfill(
        BackfillInput(rows=rows, repo=deps.repo, ledger=deps.ledger, providers=kit["providers"], clock=deps.clock, ids=deps.ids)
    )


async def _main(path: str) -> int:
    from boilpayment.postgres import PostgresLedgerStore, PostgresRepo

    db = os.environ["DATABASE_URL"]
    deps = Deps(
        clock=SystemClock(), ids=UuidIdGen(), repo=PostgresRepo(db), ledger=PostgresLedgerStore(db),
        notifier=None, providers={}, policy=None,
    )
    report = await run_backfill(Path(path).read_text(), deps, dict(os.environ))
    for r in report.results:
        print(json.dumps(dataclasses.asdict(r)))
    print(json.dumps({"ok": report.ok, "errors": report.errors}))
    return 1 if report.errors else 0


if __name__ == "__main__":
    if len(sys.argv) != 2:
        print("usage: python -m paykit.backfill <customers.csv|customers.json>", file=sys.stderr)
        sys.exit(2)
    sys.exit(asyncio.run(_main(sys.argv[1])))
`;
}

/** INTEGRATION.md section (Korean, same voice as the rest of the file). */
export function backfillIntegrationSection(
  config: PaykitConfig,
  n: number,
): string[] {
  const s = config.situation!;
  const cols = backfillColumns(config);
  const l: string[] = [];
  l.push(`## ${n}. 기존 고객 들이기`);
  l.push("");
  l.push(
    "위저드에서 이미 결제 중인 고객이 있다고 답해서 생성된 절입니다. 이 kit 을 붙이기 전의 구독과",
  );
  l.push(
    "잔액이 kit 테이블에 없으면, 다음 갱신 webhook 이 `unknown_provider_ref` 로 실패하고 잔액이 0 으로 보입니다.",
  );
  l.push(
    "옛 시스템에서 고객 목록을 뽑아 `paykit/backfill.example.csv` 의 열로 맞춘 뒤 한 번 돌립니다.",
  );
  l.push("");
  l.push("```bash");
  if (config.languages.includes("ts"))
    l.push("npx tsx paykit/backfill.ts customers.csv");
  if (config.languages.includes("py"))
    l.push("python -m paykit.backfill customers.csv");
  l.push("```");
  l.push("");
  l.push("| 열 | 내용 |");
  l.push("|---|---|");
  const desc: Record<string, string> = {
    customer_id: "우리 앱의 사용자 id. 이후 모든 kit 호출의 `customerId`",
    email: "비워도 됩니다",
    provider: `\`${s.providers.join("` · `")}\` 중 하나`,
    customer_ref: "결제사 쪽 고객 id (Stripe `cus_…`, Toss·PortOne 은 고객 키)",
    subscription_ref:
      "Stripe·Polar 구독 id. 상태·기간은 파일이 아니라 결제사에서 다시 읽습니다",
    plan_id: `\`paykit.config.json\` 의 plan id (${config.plans.map((p) => `\`${p.id}\``).join(" · ") || "위저드에서 만든 plan"})`,
    billing_key:
      "Toss·PortOne 빌링키. 다음 청구는 `schedulerTick` 이 이 키로 겁니다",
    period_start: "이미 결제된 기간의 시작 (ISO 8601, 시간대 없으면 UTC)",
    period_end: "그 기간의 끝. 이 시각이 지나면 다음 청구가 나갑니다",
    credits: "옮겨 올 크레딧 잔액. 원장에 grant 한 건으로 들어갑니다",
    credits_expire_at: "잔액 만료 시각. 비우면 만료 없음",
  };
  for (const c of cols) l.push(`| \`${c}\` | ${desc[c]} |`);
  l.push("");
  l.push(
    "행마다 `created` · `updated` · `skipped` · `error` 가 찍힙니다. 다시 돌려도 이미 들어간 행은 `skipped` 라 두 번 들어가지 않습니다.",
  );
  l.push(
    "`error` 행은 아무것도 쓰지 않습니다: 설정에 없는 plan, 결제사 쪽 고객이 `customer_ref` 와 다른 구독, 이미 끝난 구독,",
  );
  l.push(
    "다른 사용자에게 이미 연결된 구독이 여기에 해당합니다. 고친 뒤 같은 파일로 다시 돌리면 됩니다.",
  );
  l.push("");
  return l;
}
