// .env.example generator — provider keys, DB URL, notification keys.
import type { PaykitConfig } from '../config.js';

const PROVIDER_ENV: Record<string, string[]> = {
  stripe: ['STRIPE_SECRET_KEY=sk_test_...', 'STRIPE_WEBHOOK_SECRET=whsec_...'],
  polar: ['POLAR_ACCESS_TOKEN=polar_at_...', 'POLAR_WEBHOOK_SECRET=whsec_...'],
  toss: [
    'TOSS_SECRET_KEY=test_sk_...',
    'TOSS_CLIENT_KEY=test_ck_...',
    '# `paykit live` 로 자동결제 실 왕복을 검증할 때는 Toss 테스트 환경 전용 더미 카드(4906251234123456,',
    '# 유효기간 30/12, 생년월일 900101)를 씁니다 — BIN(앞 6자리)만 유효하면 되고, 테스트 환경이라 실제',
    '# 출금은 없습니다. 다른 BIN 은 빌링키는 발급돼도 결제 단계에서 NOT_SUPPORTED_CARD_TYPE 로 거부될 수',
    '# 있습니다 (2026-09-09 실측, packages/providers/toss/spec/toss.pseudo.md 참고).',
  ],
  portone: ['PORTONE_API_SECRET=...', 'PORTONE_STORE_ID=store-...', 'PORTONE_WEBHOOK_SECRET=...'],
};

export interface GenerateEnvExampleOptions {
  /** CS SDK API 키 — 위저드에서 답했으면 실값을, 비웠으면 placeholder 를 쓴다. */
  csApiKey?: string;
}

export function generateEnvExample(config: PaykitConfig, opts: GenerateEnvExampleOptions = {}): string {
  const lines: string[] = [];
  lines.push('# Generated by `paykit init` — copy to .env and fill in real values.');
  const installLines: string[] = [];
  if (config.languages.includes('ts')) installLines.push('npm install @schift/payment-kit-sdk');
  if (config.languages.includes('py')) installLines.push('pip install schift-payment-kit');
  if (installLines.length) {
    lines.push(`# Install (single package — bundles every @schift/payment-kit-* module this project uses):`);
    for (const line of installLines) lines.push(`#   ${line}`);
  }
  lines.push('');

  lines.push('# --- Database (schema-postgres) ---');
  lines.push('DATABASE_URL=postgres://user:password@localhost:5432/paykit');
  if (config.infra.logging === 'postgres') {
    lines.push('# infra.logging=postgres — provider request/response + audit events also go to `audit_log` via this URL (EC:L1-L5, docs/EDGE_CASES.md §L).');
  }
  lines.push('');

  for (const provider of config.providers) {
    lines.push(`# --- ${provider} ---`);
    for (const line of PROVIDER_ENV[provider] ?? []) lines.push(line);
    lines.push('');
  }

  if (config.infra.notify.email === 'resend') {
    lines.push('# --- Notify: Resend ---');
    lines.push('RESEND_API_KEY=re_...');
    lines.push('RESEND_FROM_EMAIL=billing@yourapp.com');
    lines.push('RESEND_TO_EMAIL=ops@yourapp.com  # fallback recipient when a notification has no per-customer email (e.g. cs.needs_human)');
    lines.push('');
  } else if (config.infra.notify.email === 'smtp') {
    lines.push('# --- Notify: SMTP ---');
    lines.push('SMTP_HOST=smtp.yourapp.com');
    lines.push('SMTP_PORT=587');
    lines.push('SMTP_USER=...');
    lines.push('SMTP_PASS=...');
    lines.push('SMTP_FROM_EMAIL=billing@yourapp.com');
    lines.push('SMTP_TO_EMAIL=ops@yourapp.com  # fallback recipient when a notification has no per-customer email (e.g. cs.needs_human)');
    lines.push('');
  }

  if (config.infra.notify.slack) {
    lines.push('# --- Notify: Slack ---');
    lines.push('SLACK_WEBHOOK_URL=https://hooks.slack.com/services/...');
    lines.push('');
  }

  if (config.cs.enabled) {
    lines.push('# --- Optional CS usage reporting --- see docs/CS_SERVER.md. Refund and recovery work without this.');
    lines.push(`PAYKIT_API_KEY=${opts.csApiKey && opts.csApiKey.trim() !== '' ? opts.csApiKey : 'pk_live_...'}`);
    lines.push('# PAYKIT_API_BASE_URL=https://api.schift.io/paykit/v1  # optional override; defaults to this in the SDK');
    lines.push('');
  }

  lines.push('# --- App ---');
  lines.push(`PAYKIT_WEBHOOK_PATH=${config.infra.webhookPath}`);

  return lines.join('\n') + '\n';
}
