// paykit/index.py generator — Python mirror of ts-entry.ts. Same selection logic; same real
// contracts verified against packages/*/py/src on 2026-09-09 (see NAMING ASSUMPTION comment
// at the top of ts-entry.ts — that note applies here too, both languages were fixed together).
//
// Python-specific calling convention (found by reading the actual .py files, not guessed):
//   - Most functions take ONE positional dataclass `input` arg (e.g. `consume(ConsumeCreditsInput(...))`).
//   - A handful take keyword-only args directly, no wrapper dataclass: usage.record, usage.check,
//     usage.flush_outbox, usage.close_period, webhook.receive, webhook.process, webhook.default_handlers.
//   - lifecycle exports `dunning` and `scheduler` as submodules (`from . import dunning, scheduler`),
//     so their Input dataclasses hang off the submodule object itself (`dunning.OnGraceExpiredInput(...)`).
import type { PaykitConfig } from '../config.js';
import { hasReasonRules, supportPy } from './support.js';
import { extrasFunctionsPy, extrasImportsPy } from './py-extras.js';

function providerImportsPy(config: PaykitConfig): string[] {
  const lines: string[] = [];
  if (config.providers.includes('stripe')) lines.push(`from boilpayment.stripe import StripeProvider`);
  if (config.providers.includes('polar')) lines.push(`from boilpayment.polar import PolarProvider`);
  if (config.providers.includes('toss')) lines.push(`from boilpayment.toss import TossProvider, TossProviderConfig`);
  if (config.providers.includes('portone')) lines.push(`from boilpayment.portone import PortoneProvider, PortoneProviderConfig`);
  return lines;
}

// EC:L1 — every provider constructor takes an optional `logger` (defaults to NoopLogger inside the
// provider itself if omitted, but we always pass the one this app built so provider.request events
// actually reach it). TossProviderConfig/PortoneProviderConfig/StripeProvider() take `logger=` as a
// keyword; PolarProvider() takes `logger=` directly (no config dataclass — see its __init__).
function providerConstructionPy(config: PaykitConfig): string[] {
  const lines: string[] = [];
  if (config.providers.includes('stripe')) lines.push(`    providers["stripe"] = StripeProvider(secret_key=_env(env, "STRIPE_SECRET_KEY"), webhook_secret=_env(env, "STRIPE_WEBHOOK_SECRET"), previous_webhook_secrets=[v.strip() for v in (env.get("STRIPE_WEBHOOK_PREVIOUS_SECRETS") or "").split(",") if v.strip()], logger=logger)`);
  if (config.providers.includes('polar')) lines.push(`    providers["polar"] = PolarProvider(access_token=_env(env, "POLAR_ACCESS_TOKEN"), webhook_secret=_env(env, "POLAR_WEBHOOK_SECRET"), previous_webhook_secrets=[v.strip() for v in (env.get("POLAR_WEBHOOK_PREVIOUS_SECRETS") or "").split(",") if v.strip()], logger=logger)`);
  // EC:E19 — no allowlist means every Toss webhook is refused at receipt (fail closed).
  if (config.providers.includes('toss')) lines.push(`    providers["toss"] = TossProvider(TossProviderConfig(secret_key=_env(env, "TOSS_SECRET_KEY"), client_key=_env(env, "TOSS_CLIENT_KEY"), allowed_webhook_ips=[ip.strip() for ip in (env.get("TOSS_WEBHOOK_ALLOWED_IPS") or "").split(",") if ip.strip()], logger=logger))`);
  if (config.providers.includes('portone')) lines.push(`    providers["portone"] = PortoneProvider(PortoneProviderConfig(api_secret=_env(env, "PORTONE_API_SECRET"), store_id=_env(env, "PORTONE_STORE_ID"), webhook_secret=_env(env, "PORTONE_WEBHOOK_SECRET"), scheduling="self", api_base=env.get("PORTONE_API_BASE") or None, previous_webhook_secrets=[v.strip() for v in (env.get("PORTONE_WEBHOOK_PREVIOUS_SECRETS") or "").split(",") if v.strip()], logger=logger))`);
  return lines;
}

/** Mirrors ts-entry's migrationModules — the .sql files this config copied (see migrations.ts). */
function migrationModulesPy(config: PaykitConfig): string[] {
  const mods = ['core', 'webhook', 'refund'];
  if (config.goods.includes('credits')) mods.push('credits');
  if (config.models.includes('usage') || config.goods.includes('usage_quota')) mods.push('usage');
  mods.push('cs');
  return mods;
}

export function generateIndexPy(config: PaykitConfig): string {
  const hasCredits = config.goods.includes('credits');
  const hasSubscription = config.models.includes('subscription');
  const hasReservations = hasCredits && config.reservations === true; // EC:C10
  const hasReports = config.reports === true; // EC:I10
  const hasUsage = config.models.includes('usage') || config.goods.includes('usage_quota');
  const selfSchedulingProviders = config.providers.filter(
    (pr) => pr === 'toss' || pr === 'portone', // EC:A43 — PortOne renews through the kit's scheduler
  );
  const hasSelfScheduler = hasSubscription && selfSchedulingProviders.length > 0;

  const l: string[] = [];
  l.push(`"""Generated by \`boilpayment init\`. This is your code now — edit freely.`);
  l.push(`Wires only the modules you selected in the wizard. See ../POLICY.md for the policy this composes.`);
  l.push(`"""`);
  l.push(`from __future__ import annotations`);
  l.push('');
  l.push(`from typing import Any`);
  l.push('');
  l.push(`from boilpayment.core import Clock, ConsoleLogger, Deps, LedgerStore, Logger, Money, NoopLogger, Notifier, Payment, ${hasSubscription && hasCredits ? 'PaymentKitError, ' : ''}PaymentProvider, Period, Plan, PlanPrice, Policy, Repo, Subscription, resolve_policy`);
  l.push(`from boilpayment.postgres import verify_schema`);
  if (config.infra.logging === 'postgres') {
    l.push(`from boilpayment.postgres import PostgresLogger`);
  }
  if (hasCredits) {
    l.push(`from boilpayment.credits import (`);
    l.push(`    ConsumeCreditsInput,
    GrantForPeriodInput,
    GrantResult,`);
    l.push(`    ExpireDueInput,`);
    l.push(`    TopupInput,`);
    l.push(`    clawback,  # available for app-level use (see ../POLICY.md); not auto-wired — needs case-specific amounts`);
    l.push(`    consume as consume_credits,`);
    l.push(`    expire_due,`);
    l.push(`    grant_for_period,  # ditto`);
    l.push(`    rollover_on_renewal,  # ditto`);
    l.push(`    topup,`);
    l.push(`)`);
  }
  if (hasSubscription) {
    // EC:A1 A3 A5 A23 — upgrade/downgrade/cancel/reactivate aliased so this file can define its own
    // thin upgrade/downgrade/cancel/reactivate wrappers below (threading policy/ledger/repo/clock/
    // ids + resolving `provider` from `sub.provider`) without shadowing the imported function in the
    // same local scope.
    l.push(`from boilpayment.lifecycle import (`);
    l.push(`    CancelInput,`);
    l.push(`    DowngradeInput,`);
    l.push(`    OnRenewalPaidInput,`);
    l.push(`    ReactivateInput,`);
    l.push(`    UpgradeInput,`);
    l.push(`    cancel as lifecycle_cancel,`);
    l.push(`    convert_trial,  # available for app-level use; not auto-wired`);
    l.push(`    downgrade as lifecycle_downgrade,`);
    l.push(`    dunning,`);
    l.push(`    on_renewal_paid,`);
    l.push(`    reactivate as lifecycle_reactivate,`);
    l.push(`    retry_on_version_conflict,`);
    l.push(`    upgrade as lifecycle_upgrade,`);
    if (hasSelfScheduler) l.push(`    scheduler,`);
    l.push(`)`);
  }
  l.push(`from boilpayment.refund import (`);
  l.push(`    EvaluateInput,`);
  l.push(`    ExecuteInput,`);
  l.push(`    OnExternalRefundInput,`);
  if (hasReasonRules(config)) l.push(`    RefundReasonInput,`);
  l.push(`    evaluate as evaluate_refund,`);
  l.push(`    execute as execute_refund,`);
  l.push(`    on_external_refund,`);
  l.push(`)`);
  if (hasUsage) {
    l.push(`from boilpayment.usage import UsageEventInput, check as check_usage, settle_due_periods, flush_outbox, record as record_usage`);
  }
  l.push(...extrasImportsPy(hasReservations, hasReports));
  l.push(`from boilpayment.webhook import default_handlers, process as process_webhook, receive as receive_webhook`);
  const notifyImports: string[] = [];
  if (config.infra.notify.email === 'resend') notifyImports.push('resend');
  if (config.infra.notify.email === 'smtp') notifyImports.push('smtp');
  if (config.infra.notify.slack) notifyImports.push('slack');
  if (notifyImports.length) l.push(`from boilpayment.notify import ${notifyImports.join(', ')}`);
  l.push(`from boilpayment.cs import (`);
  l.push(`    DisputeInput,`);
  l.push(`    HttpLicenseReporter,`);
  l.push(`    NoopLicenseReporter,`);
  l.push(`    OpenCaseInput,`);
  l.push(`    StartCheckoutInput,
  RegisterCompletedCheckoutInput,
  ApplyPurchasedGrantInput,
  FinishRefundCasesInput,
  RequestRefundInput,
  RecoverMissingGrantInput,
  RecoverMissingGrantsInput,`);
  l.push(`    dispute,`);
  l.push(`    open_case,`);
  l.push(`    start_checkout,
  register_completed_checkout as register_checkout,
  apply_purchased_grant,
  finish_refund_cases,
  request_refund,
  recover_missing_grant,
  recover_missing_grants,
  resolve_topup_credits,`);
  l.push(`)`);
  for (const line of providerImportsPy(config)) l.push(line);
  l.push('');
  l.push('');

  // A missing secret used to surface as a bare `KeyError: 'RESEND_FROM_EMAIL'` raised from inside
  // the generated file — no indication of where the value belongs or that .env.example lists it.
  // TypeScript users get this at compile time from the PaymentKitEnv interface; Python has no such
  // gate, so the check is explicit here and the message carries the fix.
  l.push(`def _env(env: dict[str, str], key: str) -> str:`);
  l.push(`    """Reads a required secret, failing at construction with a name and a fix."""`);
  l.push(`    value = env.get(key)`);
  l.push(`    if not value:`);
  l.push(`        raise RuntimeError(`);
  l.push(`            f"{key} 가 비어 있습니다. .env.example 에 있는 항목이니 .env 에 채운 뒤 다시 실행하세요."`);
  l.push(`        )`);
  l.push(`    return value`);
  l.push('');
  l.push('');

  l.push(`def _build_providers(env: dict[str, str], logger: Logger) -> dict[str, Any]:`);
  l.push(`    providers: dict[str, Any] = {}`);
  const ctor = providerConstructionPy(config);
  if (ctor.length) for (const line of ctor) l.push(line);
  else l.push(`    pass`);
  l.push(`    return providers`);
  l.push('');
  l.push('');

  l.push(`def _build_logger(env: dict[str, str]) -> Logger:`);
  l.push(`    """EC:L1-L5 (docs/EDGE_CASES.md §L) — driven by infra.logging in paykit.config.json ('${config.infra.logging}' here)."""`);
  if (config.infra.logging === 'postgres') {
    l.push(`    return PostgresLogger(_env(env, "DATABASE_URL"))`);
  } else if (config.infra.logging === 'console') {
    l.push(`    return ConsoleLogger()`);
  } else {
    l.push(`    return NoopLogger()`);
  }
  l.push('');
  l.push('');

  l.push(`def _build_notifier(env: dict[str, str]) -> Notifier:`);
  if (notifyImports.length === 0) {
    l.push(`    class _NoopNotifier:`);
    l.push(`        async def send(self, n: dict[str, Any]) -> None:`);
    l.push(`            return None`);
    l.push(`    return _NoopNotifier()  # 알림 없음 (no notify adapter selected)`);
  } else {
    l.push(`    adapters = [`);
    if (config.infra.notify.email === 'resend') l.push(`        resend(api_key=_env(env, "RESEND_API_KEY"), from_=_env(env, "RESEND_FROM_EMAIL"), to=_env(env, "RESEND_TO_EMAIL")),`);
    if (config.infra.notify.email === 'smtp') l.push(`        smtp(host=_env(env, "SMTP_HOST"), port=int(_env(env, "SMTP_PORT")), user=_env(env, "SMTP_USER"), password=_env(env, "SMTP_PASS"), from_=_env(env, "SMTP_FROM_EMAIL"), to=_env(env, "SMTP_TO_EMAIL")),`);
    if (config.infra.notify.slack) l.push(`        slack(webhook_url=_env(env, "SLACK_WEBHOOK_URL")),`);
    l.push(`    ]`);
    l.push('');
    l.push(`    class _FanoutNotifier:`);
    l.push(`        async def send(self, n: dict[str, Any]) -> None:`);
    l.push(`            for a in adapters:`);
    l.push(`                await a.send(n)`);
    l.push(`    return _FanoutNotifier()`);
  }
  l.push('');
  l.push('');

  l.push(`def create_payment_kit(config: dict[str, Any], deps: Deps, env: dict[str, str], providers_override: dict[str, PaymentProvider] | None = None):`);
  l.push(`    """Composes the selected modules per paykit.config.json. \`env\` carries provider/notify secrets."""`);
  l.push(`    policy: Policy = resolve_policy(config["policy"])`);
  l.push(`    # EC:L1-L5 — deps.logger (if the caller already built one) wins; otherwise built from infra.logging.`);
  l.push(`    logger: Logger = deps.logger or _build_logger(env)`);
  l.push(`    providers = providers_override if providers_override is not None else _build_providers(env, logger)`);
  l.push(`    notifier = deps.notifier or _build_notifier(env)`);
  l.push(`    ledger = deps.ledger`);
  l.push(`    repo = deps.repo`);
  l.push(`    clock = deps.clock`);
  l.push(`    ids = deps.ids`);
  l.push('');

  l.push(`    # EC:I5 — reports billable CS case transitions to Schift's license server (docs/CS_SERVER.md).`);
  l.push(`    # Falls back to NoopLicenseReporter (never reports, never raises) when no API key is set.`);
  l.push(`    api_key = env.get("PAYKIT_API_KEY") if ${config.cs.enabled ? "True" : "False"} else None`);
  l.push(`    api_base_url = env.get("PAYKIT_API_BASE_URL")`);
  l.push(`    license_reporter = (`);
  l.push(`        HttpLicenseReporter(api_key=api_key, **({"base_url": api_base_url} if api_base_url else {}))`);
  l.push(`        if api_key`);
  l.push(`        else NoopLicenseReporter()`);
  l.push(`    )`);
  l.push('');

  l.push(`    # Adapts open_case to the small case-opener Protocols refund.on_external_refund/execute expect,`);
  l.push(`    # so refund/execute stay decoupled from importing boilpayment.cs directly (EC:D8/D12).`);
  l.push(`    class _CaseOpener:`);
  l.push(`        async def open_reconcile_mismatch_case(self, *, customer_id: str, reference_id: str, reason: str) -> None:`);
  l.push(`            await open_case(OpenCaseInput(customer_id=customer_id, kind="reconcile_mismatch", reference_id=reference_id, policy=policy, repo=repo, clock=clock, ids=ids))`);
  l.push(`        async def open_refund_failed_case(self, *, customer_id: str, reference_id: str, reason: str, needs: str | None = None) -> None:`);
  l.push(`            await open_case(OpenCaseInput(customer_id=customer_id, kind="refund_failed", reference_id=reference_id, policy=policy, repo=repo, clock=clock, ids=ids))`);
  l.push(`    case_opener = _CaseOpener()`);
  l.push('');

  l.push(`    class _RefundDeps:`);
  l.push(`        async def on_external_refund(self, *, event: Any, ledger: Any, repo: Any, cs: Any = None) -> Any:`);
  l.push(`            result = await on_external_refund(OnExternalRefundInput(event=event, ledger=ledger, repo=repo, cs=case_opener, clock=clock, ids=ids))
            await finish_refund_cases(FinishRefundCasesInput(repo=repo, clock=clock, notifier=notifier, reporter=license_reporter))
            return result`);
  l.push('');

  if (hasSubscription) {
    l.push(`    class _LifecycleDunningDeps:`);
    l.push(`        async def on_payment_failed(self, *, sub: Any, policy: Any, repo: Any, notifier: Any, clock: Any) -> Any:`);
    l.push(`            return await dunning.on_payment_failed(dunning.OnPaymentFailedInput(sub=sub, policy=policy, repo=repo, notifier=notifier, clock=clock))`);
    l.push('');
    l.push(`    class _LifecycleDeps:`);
    l.push(`        dunning = _LifecycleDunningDeps()`);
    l.push(`        async def on_renewal_paid(self, *, sub: Any, payment: Any, policy: Any, ledger: Any, repo: Any, clock: Any) -> Any:`);
    l.push(`            return await on_renewal_paid(OnRenewalPaidInput(sub=sub, payment=payment, policy=policy, ledger=ledger, repo=repo, clock=clock))`);
    l.push('');
  }
  if (hasCredits) {
    l.push(`    class _CreditsDeps:`);
    l.push(`        async def topup(self, *, customer_id: str, payment: Any, credits: int | None, policy: Any, ledger: Any, clock: Any, repo: Any) -> Any:`);
    l.push(`            return await apply_purchased_grant(ApplyPurchasedGrantInput(customer_id=customer_id, payment_id=payment.id, policy=policy, providers=providers, repo=repo, ledger=ledger, clock=clock, ids=ids, grants=support_grants))`);
    l.push('');
  }
  l.push(`    class _CsDeps:`);
  l.push(`        async def dispute(self, *, event: Any, policy: Any, ledger: Any, repo: Any, notifier: Any) -> Any:`);
  l.push(`            return await dispute(DisputeInput(event=event, policy=policy, ledger=ledger, repo=repo, notifier=notifier, clock=clock, ids=ids, reporter=license_reporter))`);
  l.push('');

  if (hasCredits) {
    l.push(`    async def _resolve_topup_credits(payment):`);
    l.push(`        return await resolve_topup_credits(payment=payment, repo=repo)`);
  }
  l.push(supportPy(hasCredits, hasReasonRules(config)));
  l.push(`    handlers = default_handlers(`);
  l.push(`        policy=policy, ledger=ledger, repo=repo, notifier=notifier, clock=clock, ids=ids,`);
  l.push(`        lifecycle=${hasSubscription ? '_LifecycleDeps()' : 'None'},`);
  l.push(`        credits=${hasCredits ? '_CreditsDeps()' : 'None'},`);
  l.push(`        refund=_RefundDeps(),`);
  if (hasCredits) l.push(`        resolve_topup_credits=_resolve_topup_credits,`);
  l.push(`        cs=_CsDeps(),`);
  l.push(`    )`);
  l.push('');

  l.push(`    async def checkout(*, customer_id: str, plan_id: str, provider: str, currency: str, request_id: str, success_url: str, cancel_url: str):`);
  l.push(`        return await start_checkout(StartCheckoutInput(customer_id=customer_id, plan_id=plan_id, provider=provider, currency=currency, request_id=request_id, success_url=success_url, cancel_url=cancel_url, policy=policy, providers=providers, repo=repo, ledger=ledger, clock=clock, ids=ids))`);
  l.push(`    async def register_completed_checkout(*, customer_id: str, checkout_id: str, payment_ref: str, subscription_ref: str | None = None):`);
  l.push(`        return await register_checkout(RegisterCompletedCheckoutInput(customer_id=customer_id, checkout_id=checkout_id, payment_ref=payment_ref, subscription_ref=subscription_ref, policy=policy, providers=providers, repo=repo, ledger=ledger, clock=clock, ids=ids))`);
  if (hasSubscription) {
    l.push(`    async def upgrade(**kwargs: Any):`);
    l.push(`        """EC:A1 A2 A8 J1-J5 — mid-cycle plan upgrade (immediate proration or scheduled next-period, per policy). Resolves \`provider\` from \`sub.provider\` unless passed explicitly."""`);
    l.push(`        sub = kwargs["sub"]`);
    l.push(`        provider = kwargs.pop("provider", None) or providers.get(sub.provider)`);
    l.push(`        if provider is None:`);
    l.push(`            raise ValueError(f"provider not configured: {sub.provider}")`);
    l.push(`        return await lifecycle_upgrade(UpgradeInput(policy=policy, ledger=ledger, repo=repo, clock=clock, ids=ids, provider=provider, **kwargs))`);
    l.push('');
    l.push(`    async def downgrade(**kwargs: Any):`);
    l.push(`        """EC:A3 A4 J1-J5 — downgrade, optionally clawing back the credit surplus immediately (per policy)."""`);
    l.push(`        sub = kwargs["sub"]`);
    l.push(`        provider = kwargs.pop("provider", None) or providers.get(sub.provider)`);
    l.push(`        if provider is None:`);
    l.push(`            raise ValueError(f"provider not configured: {sub.provider}")`);
    l.push(`        return await lifecycle_downgrade(DowngradeInput(policy=policy, ledger=ledger, repo=repo, clock=clock, ids=ids, provider=provider, **kwargs))`);
    l.push('');
    l.push(`    async def cancel(**kwargs: Any):`);
    l.push(`        """EC:A5 A6 A10 I4 J1-J5 — cancel now or at period end; resolves outstanding credits per policy."""`);
    l.push(`        sub = kwargs["sub"]`);
    l.push(`        provider = kwargs.pop("provider", None) or providers.get(sub.provider)`);
    l.push(`        if provider is None:`);
    l.push(`            raise ValueError(f"provider not configured: {sub.provider}")`);
    l.push(`        return await lifecycle_cancel(CancelInput(policy=policy, ledger=ledger, repo=repo, clock=clock, provider=provider, **kwargs))`);
    l.push('');
    l.push(`    async def reactivate(**kwargs: Any):`);
    l.push(`        """EC:A23 — undo an EC:A5 end-of-period cancel while the subscription is still active (the mirror image of cancel's credit revoke)."""`);
    l.push(`        sub = kwargs["sub"]`);
    l.push(`        provider = kwargs.pop("provider", None) or providers.get(sub.provider)`);
    l.push(`        if provider is None:`);
    l.push(`            raise ValueError(f"provider not configured: {sub.provider}")`);
    l.push(`        return await lifecycle_reactivate(ReactivateInput(policy=policy, ledger=ledger, repo=repo, clock=clock, provider=provider, **kwargs))`);
    l.push('');
  }
  if (hasCredits) {
    if (hasSubscription) {
      l.push(`    async def current_subscription(customer_id: str) -> Subscription | None:`);
      l.push(`        """EC:C11 — the customer's current (latest) subscription, for entitlement checks the kit owns."""`);
      l.push(`        subs = await repo.subscriptions.list(customer_id=customer_id)`);
      l.push(`        return max(subs, key=lambda s: s.created_at) if subs else None`);
      l.push('');
    }
    l.push(`    async def consume(**kwargs: Any):`);
    l.push(`        """EC:B3 B4 B5 B14 — atomic consume against the ledger."""`);
    if (hasSubscription) {
      l.push(`        # EC:C11 — an unpaid subscription (paused, incomplete) spends nothing; canceled/expired keep bought credits.`);
      l.push(`        sub = await current_subscription(kwargs["customer_id"])`);
      l.push(`        if sub is not None and sub.status in ("paused", "incomplete"):  # INACTIVE_SUBSCRIPTION_STATUSES`);
      l.push(`            raise PaymentKitError(f"subscription {sub.id} is {sub.status}", "subscription_inactive")`);
      l.push(`        # EC:A44 — policy.dunning.usage_during_grace = 'block' stops spending while a renewal is unpaid.`);
      l.push(`        if sub is not None and sub.status == "past_due" and policy.dunning.usage_during_grace == "block":`);
      l.push(`            raise PaymentKitError(f"subscription {sub.id} is past due", "grace_usage_blocked")`);
    }
    l.push(`        return await consume_credits(ConsumeCreditsInput(policy=policy, ledger=ledger, clock=clock, **kwargs))`);
  } else {
    l.push(`    async def consume(**kwargs: Any):`);
    l.push(`        raise RuntimeError("credits not selected in paykit.config.json (goods)")`);
  }
  l.push('');
  if (hasUsage) {
    l.push(`    async def record(*, event: UsageEventInput, sub: Subscription):`);
    l.push(`        """EC:C2 C3 — usage event ingestion."""`);
    l.push(`        return await record_usage(event=event, sub=sub, policy=policy, repo=repo, clock=clock, ids=ids, provider=providers.get(sub.provider), plan=await repo.plans.get(sub.plan_id))`);
    l.push('');
    l.push(`    async def check_quota(**kwargs: Any):`);
    l.push(`        """EC:C1 C5 C6 — quota/overage check."""`);
    l.push(`        return await check_usage(policy=policy, repo=repo, ledger=ledger, clock=clock, **kwargs)`);
    l.push('');
  }
  l.push(...extrasFunctionsPy(hasReservations, hasReports, hasSubscription));
  l.push(`    async def refund(extra: dict[str, Any] | None = None, **kwargs: Any):`);
  l.push(`        """EC:D* — policy-driven refund evaluation. Caller executes with a resolved provider."""`);
  l.push(`        decision = await evaluate_refund(EvaluateInput(policy=policy, ledger=ledger, repo=repo, clock=clock, **kwargs))`);
  l.push('');
  l.push(`        async def execute(provider: Any):`);
  l.push(`            return await execute_refund(ExecuteInput(decision=decision, provider=provider, ledger=ledger, repo=repo, clock=clock, ids=ids, extra=extra, cs=case_opener))`);
  l.push('');
  l.push(`        return decision, execute`);
  l.push('');
  const tossOrigin = config.providers.includes('toss'); // EC:E18 — Toss allowlists by peer address
  l.push(`    async def handle_webhook(raw_body: str, headers: dict[str, str], provider: str | None = None${tossOrigin ? ', remote_address: str | None = None' : ''}):`);
  l.push(`        """EC:E3 E4 E5 E13 — webhook receipt is provider-scoped. See ./webhook.py for framework snippets."""`);
  l.push(`        configured = list(providers.keys())`);
  l.push(`        provider_name = provider or (configured[0] if len(configured) == 1 else None)`);
  l.push(`        if provider_name is None:`);
  l.push(`            raise ValueError("multiple providers configured — pass provider= to handle_webhook")`);
  l.push(`        prov = providers.get(provider_name)`);
  l.push(`        if prov is None:`);
  l.push(`            raise ValueError(f"provider not configured: {provider_name}")`);
  l.push(`        received = await receive_webhook(provider=prov, headers=headers, raw_body=raw_body, repo=repo, clock=clock${tossOrigin ? ', remote_address=remote_address' : ''})`);
  l.push(`        if received.status == 200 and received.event_id:`);
  l.push(`            await process_webhook(event_id=received.event_id, providers=providers, handlers=handlers, repo=repo, clock=clock)`);
  l.push(`        return received`);
  l.push('');

  l.push(`    async def _cron_expire_due():`);
  if (hasCredits) {
    l.push(`        # credits.expire_due is per-customer — sweep all customers.`);
    l.push(`        customers = await repo.customers.list()`);
    l.push(`        for customer in customers:`);
    l.push(`            await expire_due(ExpireDueInput(ledger=ledger, clock=clock, customer_id=customer.id))`);
  } else {
    l.push(`        return None`);
  }
  l.push('');
  l.push(`    async def _cron_dunning_sweep():`);
  if (hasSubscription) {
    l.push(`        due = await repo.subscriptions.list(status="past_due")`);
    l.push(`        now = clock.now()`);
    l.push(`        for stale in due:`);
    l.push(`            # EC:K1 -- the list read and the write inside on_grace_expired are far apart;`);
    l.push(`            # another writer (webhook, scheduler) can bump the row in between. Re-read.`);
    l.push(`            async def _attempt(sub_id: str = stale.id):`);
    l.push(`                sub = await repo.subscriptions.get(sub_id)`);
    l.push(`                if sub is None:`);
    l.push(`                    return`);
    l.push(`                if sub.grace_until and sub.grace_until <= now:`);
    l.push(`                    await dunning.on_grace_expired(dunning.OnGraceExpiredInput(sub=sub, policy=policy, ledger=ledger, repo=repo, notifier=notifier, clock=clock))`);
    l.push('');
    l.push(`            await retry_on_version_conflict(_attempt)`);
  } else {
    l.push(`        return None`);
  }
  l.push('');
  l.push(`    async def _cron_close_periods():`);
  if (hasUsage) {
    l.push(`        return await settle_due_periods(policy=policy, repo=repo, ledger=ledger, providers=providers, clock=clock)`);
  } else {
    l.push(`        return None`);
  }
  l.push('');
  l.push(`    async def _cron_flush_outbox():`);
  if (hasUsage) {
    l.push(`        return await flush_outbox(repo=repo, providers=providers, clock=clock)`);
  } else {
    l.push(`        return None`);
  }
  l.push('');
  l.push(`    async def _cron_scheduler_tick():`);
  if (hasSelfScheduler) {
    l.push(`        # self-scheduling providers: ${selfSchedulingProviders.join(', ')} (EC:A43: Toss and PortOne always self).`);
    l.push(`        self_scheduling_providers = [${selfSchedulingProviders.map((p) => `"${p}"`).join(', ')}]`);
    l.push(`        charged = []`);
    l.push(`        failed = []`);
    l.push(`        errors = []`);
    l.push(`        for name in self_scheduling_providers:`);
    l.push(`            provider = providers.get(name)`);
    l.push(`            if provider is None:`);
    l.push(`                continue`);
    l.push(`            result = await scheduler.tick(scheduler.SchedulerTickInput(provider=provider, repo=repo, policy=policy, ledger=ledger, clock=clock, ids=ids, notifier=notifier))`);
    l.push(`            charged.extend(result.charged)`);
    l.push(`            failed.extend(result.failed)`);
    l.push(`            errors.extend({"subscription_id": e.subscription_id, "code": e.code, "message": e.message} for e in result.errors)`);
    l.push(`            # EC:A34 -- due dunning retries charge through the same per-period attempt records as the tick.`);
    l.push(`            for item in await dunning.retry_due(dunning.RetryDueInput(repo=repo, clock=clock)):`);
    l.push(`                sub = await repo.subscriptions.get(item.payload.get("subscriptionId", item.payload.get("subscription_id")))`);
    l.push(`                if sub is None or sub.provider != name:`);
    l.push(`                    continue`);
    l.push(`                try:`);
    l.push(`                    retry = await dunning.run_retry(dunning.RunRetryInput(item=item, provider=provider, repo=repo, ledger=ledger, policy=policy, notifier=notifier, clock=clock))`);
    l.push(`                    if retry.outcome == "recovered" and retry.sub is not None:`);
    l.push(`                        charged.append(retry.sub)`);
    l.push(`                except Exception as err:  # noqa: BLE001 -- reported, never dropped (EC:A36)`);
    l.push(`                    errors.append({"subscription_id": sub.id, "code": getattr(err, "code", "dunning_retry_error"), "message": str(err)})`);
    l.push(`        # EC:A36 -- never dropped: every unresolved or failed renewal is logged and returned.`);
    l.push(`        for e in errors:`);
    l.push(`            await logger.log({"level": "error", "event": "scheduler.error", **e})`);
    l.push(`        return {"charged": charged, "failed": failed, "errors": errors}`);
  } else {
    l.push(`        return {"charged": [], "failed": [], "errors": []}`);
  }
  l.push('');
  l.push(`    async def _cron_reconcile(since):`);
  l.push(`        return ${hasCredits ? 'await recover_missing_grants(RecoverMissingGrantsInput(policy=policy, providers=providers, repo=repo, ledger=ledger, clock=clock, ids=ids, notifier=notifier, grants=support_grants, since=since, reporter=license_reporter))' : '[]'}`);
  l.push('');

  l.push(`    cron = {`);
  l.push(`        "expire_due": _cron_expire_due,`);
  l.push(`        "dunning_sweep": _cron_dunning_sweep,`);
  l.push(`        "close_periods": _cron_close_periods,`);
  l.push(`        "flush_outbox": _cron_flush_outbox,`);
  l.push(`        "scheduler_tick": _cron_scheduler_tick,`);
  l.push(`        "reconcile": _cron_reconcile,`);
  if (hasReservations) l.push(`        "sweep_reservations": lambda: sweep_reservations(repo=repo, ledger=ledger, clock=clock),`);
  l.push(`    }`);
  l.push('');
  l.push(`    async def verify_db_schema():`);
  l.push(`        """Call at boot, before serving traffic: fails loudly when the database is behind this`);
  l.push(`        build instead of letting the first query die on a missing column in production."""`);
  l.push(`        return await verify_schema(conninfo=_env(env, "DATABASE_URL"), modules=${JSON.stringify(migrationModulesPy(config))})`);
  l.push('');
  l.push(`    async def initialize(*, verify_schema_first: bool = True):`);
  l.push(`        if verify_schema_first:`);
  l.push(`            await verify_db_schema()`);
  l.push(`        for plan in config["plans"]:`);
  l.push(`            await repo.plans.put(Plan(id=plan["id"], name=plan["name"], interval=plan["interval"], credits_per_period=plan["creditsPerPeriod"], usage_included=plan["usageIncluded"], trial_days=plan["trialDays"], prices=[PlanPrice(currency=price["currency"], amount_minor=price["amountMinor"], provider_price_refs=price.get("providerPriceRefs")) for price in plan["prices"]]))`);
  l.push(`    return {`);
  l.push(`        "verify_schema": verify_db_schema,`);
  l.push(`        "handle_webhook": handle_webhook,`);
  l.push(`        "consume": consume,`);
  if (hasUsage) {
    l.push(`        "record": record,`);
    l.push(`        "check_quota": check_quota,`);
  }
  l.push(`        "checkout": checkout,`);
  l.push(`        "register_completed_checkout": register_completed_checkout,`);
  l.push(`        "initialize": initialize,`);
  if (hasSubscription) {
    l.push(`        "upgrade": upgrade,`);
    l.push(`        "downgrade": downgrade,`);
    l.push(`        "cancel": cancel,`);
    l.push(`        "reactivate": reactivate,`);
  }
  l.push(`        "refund": refund,`);
  l.push(`        "support": support,`);
  if (hasReservations) l.push(`        "reservations": reservations,`);
  if (hasReports) l.push(`        "reports": reports,`);
  l.push(`        "cron": cron,`);
  l.push(`        "providers": providers,`);
  l.push(`        "notifier": notifier,`);
  l.push(`        "logger": logger,`);
  l.push(`        "policy": policy,`);
  l.push(`        "license_reporter": license_reporter,  # EC:I5 — pass to regrant/refund_assist you call directly`);
  l.push(`    }`);
  l.push('');

  return l.join('\n');
}
