// paykit/index.ts generator — composes ONLY the selected modules into createPaymentKit().
//
// Import names and function signatures below were verified against the actual built packages
// (packages/*/ts/src/index.ts) on 2026-09-09, not guessed from docs/ARCHITECTURE.md §3.5 alone.
// Notable real-world deviations from the ARCHITECTURE.md pseudo-signatures, kept in generated
// code comments too (see "계약 변경 제안" in the final report):
//   - lifecycle exports `dunning` and `scheduler` as namespace objects (`dunning.onGraceExpired`,
//     `scheduler.tick`), not flat `dunningOnGraceExpired`/`schedulerTick`.
//   - credits.expireDue takes a required `customerId` (per-customer), not a global batch call.
//   - usage.flushOutbox takes the whole `providers` map in one call, not one call per provider.
//   - lifecycle.scheduler.tick returns `{ charged: Subscription[], failed: Subscription[] }`
//     (arrays), not counts.
//   - webhook.receive takes the resolved `PaymentProvider` instance (not a provider name string)
//     and returns `eventId` (camelCase); webhook.process needs `clock` too.
//   - webhook.defaultHandlers takes duck-typed `lifecycle`/`credits`/`refund`/`cs` dep bags
//     (see packages/webhook/ts/src/handlers.ts) instead of importing those packages itself.
//   - refund.execute and cs.dispute/openCase/reconcile all require `ids: IdGen` in addition to
//     what ARCHITECTURE.md's short-form signature lists.
import type { PaykitConfig } from '../config.js';
import { hasReasonRules, supportTs } from './support.js';

function providerImportsTs(config: PaykitConfig): string {
  const lines: string[] = [];
  if (config.providers.includes('stripe')) lines.push(`import { StripeProvider } from 'boilpayment-sdk/stripe';`);
  if (config.providers.includes('polar')) lines.push(`import { PolarProvider } from 'boilpayment-sdk/polar';`);
  if (config.providers.includes('toss')) lines.push(`import { TossProvider } from 'boilpayment-sdk/toss';`);
  if (config.providers.includes('portone')) lines.push(`import { PortoneProvider } from 'boilpayment-sdk/portone';`);
  return lines.join('\n');
}

// EC:L1 — every provider constructor takes an optional `logger` (defaults to NoopLogger inside
// the provider itself if omitted here, but we always pass the one this app built so provider.request
// events actually reach it).
function providerConstructionTs(config: PaykitConfig): string {
  const lines: string[] = [];
  if (config.providers.includes('stripe')) {
    lines.push(`  providers.stripe = new StripeProvider({ secretKey: env.STRIPE_SECRET_KEY, webhookSecret: env.STRIPE_WEBHOOK_SECRET, logger });`);
  }
  if (config.providers.includes('polar')) {
    lines.push(`  providers.polar = new PolarProvider({ accessToken: env.POLAR_ACCESS_TOKEN, webhookSecret: env.POLAR_WEBHOOK_SECRET, logger });`);
  }
  if (config.providers.includes('toss')) {
    lines.push(`  providers.toss = new TossProvider({ secretKey: env.TOSS_SECRET_KEY, clientKey: env.TOSS_CLIENT_KEY, logger });`);
  }
  if (config.providers.includes('portone')) {
    lines.push(`  providers.portone = new PortoneProvider({ apiSecret: env.PORTONE_API_SECRET, storeId: env.PORTONE_STORE_ID, webhookSecret: env.PORTONE_WEBHOOK_SECRET, logger });`);
  }
  return lines.join('\n');
}

/** The schema-postgres module names matching the .sql files this config copied (see migrations.ts). */
function migrationModules(config: PaykitConfig): string[] {
  const mods = ['core', 'webhook', 'refund'];
  if (config.goods.includes('credits')) mods.push('credits');
  if (config.models.includes('usage') || config.goods.includes('usage_quota')) mods.push('usage');
  mods.push('cs');
  return mods;
}

export function generateIndexTs(config: PaykitConfig): string {
  const hasCredits = config.goods.includes('credits');
  const hasSubscription = config.models.includes('subscription');
  const hasUsage = config.models.includes('usage') || config.goods.includes('usage_quota');
  // Toss has no native subscriptions and is always self-scheduled. Portone follows
  // infra.scheduler (defaults to provider-side V2 schedule API).
  const selfSchedulingProviders = config.providers.filter(
    (pr) => pr === 'toss' || (pr === 'portone' && config.infra.scheduler === 'self'),
  );
  const hasSelfScheduler = hasSubscription && selfSchedulingProviders.length > 0;
  const hasReservations = hasCredits && config.reservations === true; // EC:C10
  const hasReports = config.reports === true; // EC:I10

  const l: string[] = [];
  l.push(`// Generated by \`boilpayment init\`. This is your code now — edit freely.`);
  l.push(`// Wires only the modules you selected in the wizard. See ../POLICY.md for the policy this composes.`);
  l.push(`import type { Deps, Notifier, PaymentProvider, ProviderName, Policy, Subscription, Logger } from 'boilpayment-sdk/core';`);
  l.push(`import { resolvePolicy, NoopLogger, ConsoleLogger } from 'boilpayment-sdk/core';`);
  l.push(`import { verifySchema } from 'boilpayment-sdk/postgres';`);
  if (config.infra.logging === 'postgres') {
    l.push(`import { PostgresLogger, createPool } from 'boilpayment-sdk/postgres';`);
  }
  if (hasCredits) {
    l.push(`import { grantForPeriod, consume as consumeCredits, rolloverOnRenewal, clawback, expireDue, topup } from 'boilpayment-sdk/credits';`);
  }
  if (hasSubscription) {
    l.push(
      // EC:A1 A3 A5 A23 — upgrade/downgrade/cancel/reactivate aliased so this file can define its
      // own thin `upgrade`/`downgrade`/`cancel`/`reactivate` wrappers below (threading policy/
      // ledger/repo/clock/ids + resolving `provider` from `sub.provider`) without shadowing the
      // imported function.
      `import { upgrade as lifecycleUpgrade, downgrade as lifecycleDowngrade, cancel as lifecycleCancel, reactivate as lifecycleReactivate, convertTrial, onRenewalPaid, dunning, retryOnVersionConflict${hasSelfScheduler ? ', scheduler' : ''} } from 'boilpayment-sdk/lifecycle';`,
    );
  }
  l.push(`import { evaluate as evaluateRefund, execute as executeRefund, onExternalRefund } from 'boilpayment-sdk/refund';`);
  if (hasUsage) {
    l.push(`import { record as recordUsage, check as checkUsage, settleDuePeriods, flushOutbox } from 'boilpayment-sdk/usage';`);
  }
  if (hasReservations) {
    l.push(`import { reserve as reserveBudget, commit as commitReservation, release as releaseReservation, sweepReservations, listReservations } from 'boilpayment-sdk/usage';`);
  }
  l.push(`import { receive as receiveWebhook, process as processWebhook, defaultHandlers } from 'boilpayment-sdk/webhook';`);
  const notifyImports: string[] = [];
  if (config.infra.notify.email === 'resend') notifyImports.push('resend');
  if (config.infra.notify.email === 'smtp') notifyImports.push('smtp');
  if (config.infra.notify.slack) notifyImports.push('slack');
  if (notifyImports.length) l.push(`import { ${notifyImports.join(', ')} } from 'boilpayment-sdk/notify';`);
  if (hasReports) l.push(`import { settlementReport } from 'boilpayment-sdk/cs';`);
  l.push(`import { startCheckout, registerCompletedCheckout as registerCheckout, applyPurchasedGrant, finishRefundCases, requestRefund, recoverMissingGrant, recoverMissingGrants, resolveTopupCredits, dispute, openCase, HttpLicenseReporter, NoopLicenseReporter } from 'boilpayment-sdk/cs';`);
  const providerImports = providerImportsTs(config);
  if (providerImports) l.push(providerImports);
  l.push('');

  l.push(`export interface PaymentKitEnv {`);
  l.push(`  DATABASE_URL: string;`);
  if (config.providers.includes('stripe')) { l.push(`  STRIPE_SECRET_KEY: string;`); l.push(`  STRIPE_WEBHOOK_SECRET: string;`); }
  if (config.providers.includes('polar')) { l.push(`  POLAR_ACCESS_TOKEN: string;`); l.push(`  POLAR_WEBHOOK_SECRET: string;`); }
  if (config.providers.includes('toss')) { l.push(`  TOSS_SECRET_KEY: string;`); l.push(`  TOSS_CLIENT_KEY: string;`); }
  if (config.providers.includes('portone')) { l.push(`  PORTONE_API_SECRET: string;`); l.push(`  PORTONE_STORE_ID: string;`); l.push(`  PORTONE_WEBHOOK_SECRET: string;`); }
  if (config.infra.notify.email === 'resend') { l.push(`  RESEND_API_KEY: string;`); l.push(`  RESEND_FROM_EMAIL: string;`); l.push(`  RESEND_TO_EMAIL: string; // fallback recipient when a notification has no per-customer email`); }
  if (config.infra.notify.email === 'smtp') { l.push(`  SMTP_HOST: string; SMTP_PORT: string; SMTP_USER: string; SMTP_PASS: string; SMTP_FROM_EMAIL: string;`); l.push(`  SMTP_TO_EMAIL: string; // fallback recipient when a notification has no per-customer email`); }
  if (config.infra.notify.slack) l.push(`  SLACK_WEBHOOK_URL: string;`);
  l.push(`  /** CS SDK API 키 — docs/CS_SERVER.md. 비어 있으면 NoopLicenseReporter 로 폴백 (케이스 사용량이 서버에 보고되지 않음). */`);
  l.push(`  PAYKIT_API_KEY?: string;`);
  l.push(`  PAYKIT_API_BASE_URL?: string; // 기본값: HttpLicenseReporter 의 baseUrl 기본값 (docs/CS_SERVER.md)`);
  l.push(`}`);
  l.push('');

  l.push(`export interface PaymentKitDeps extends Omit<Deps, 'providers' | 'notifier' | 'policy'> {`);
  l.push(`  env: PaymentKitEnv;`);
  l.push(`  providers?: Partial<Record<ProviderName, PaymentProvider>>;`);
  l.push(`  notifier?: Notifier;`);
  l.push(`}`);
  l.push('');

  l.push(`function buildProviders(env: PaymentKitEnv, logger: Logger): Partial<Record<ProviderName, PaymentProvider>> {`);
  l.push(`  const providers: Partial<Record<ProviderName, PaymentProvider>> = {};`);
  const providerCtor = providerConstructionTs(config);
  if (providerCtor) l.push(providerCtor);
  l.push(`  return providers;`);
  l.push(`}`);
  l.push('');

  l.push(`/** EC:L1-L5 (docs/EDGE_CASES.md §L) — driven by infra.logging in paykit.config.json ('${config.infra.logging}' here). */`);
  l.push(`function buildLogger(env: PaymentKitEnv): Logger {`);
  if (config.infra.logging === 'postgres') {
    l.push(`  return new PostgresLogger(createPool(env.DATABASE_URL));`);
  } else if (config.infra.logging === 'console') {
    l.push(`  return new ConsoleLogger();`);
  } else {
    l.push(`  return new NoopLogger();`);
  }
  l.push(`}`);
  l.push('');

  l.push(`function buildNotifier(env: PaymentKitEnv): Notifier {`);
  if (notifyImports.length === 0) {
    l.push(`  return { send: async () => {} }; // 알림 없음 (no notify adapter selected)`);
  } else {
    l.push(`  const adapters: Notifier[] = [`);
    if (config.infra.notify.email === 'resend') l.push(`    resend({ apiKey: env.RESEND_API_KEY, from: env.RESEND_FROM_EMAIL, to: env.RESEND_TO_EMAIL }),`);
    if (config.infra.notify.email === 'smtp') l.push(`    smtp({ host: env.SMTP_HOST, port: Number(env.SMTP_PORT), auth: { user: env.SMTP_USER, pass: env.SMTP_PASS }, from: env.SMTP_FROM_EMAIL, to: env.SMTP_TO_EMAIL }),`);
    if (config.infra.notify.slack) l.push(`    slack({ webhookUrl: env.SLACK_WEBHOOK_URL }),`);
    l.push(`  ];`);
    l.push(`  return { send: async (n) => { await Promise.all(adapters.map((a) => a.send(n))); } };`);
  }
  l.push(`}`);
  l.push('');

  l.push(`/** Composes the selected modules per paykit.config.json. deps.env carries provider/notify secrets. */`);
  l.push(`export function createPaymentKit(config: typeof import('../paykit.config.json'), deps: PaymentKitDeps) {`);
  // paykit.config.json is plain JSON: every enum reads as `string`, so a direct cast to
  // Partial<Policy> stops overlapping as the Policy grows. resolvePolicy validates it at runtime.
  l.push(`  const policy: Policy = resolvePolicy(config.policy as unknown as Partial<Policy>);`);
  l.push(`  // EC:L1-L5 — deps.logger (if the caller already built one) wins; otherwise built from infra.logging.`);
  l.push(`  const logger: Logger = deps.logger ?? buildLogger(deps.env);`);
  l.push(`  const providers = deps.providers ?? buildProviders(deps.env, logger);`);
  l.push(`  const notifier = deps.notifier ?? buildNotifier(deps.env);`);
  l.push(`  const full: Deps = { ...deps, policy, providers, notifier, logger };`);
  l.push('');

  l.push(`  // EC:I5 — reports billable CS case transitions to Schift's license server (docs/CS_SERVER.md).`);
  l.push(`  // Falls back to NoopLicenseReporter (never reports, never throws) when no API key is set.`);
  if (config.cs.enabled) {
    l.push(`  const licenseReporter = deps.env.PAYKIT_API_KEY`);
    l.push(`    ? new HttpLicenseReporter({ apiKey: deps.env.PAYKIT_API_KEY, baseUrl: deps.env.PAYKIT_API_BASE_URL })`);
    l.push(`    : new NoopLicenseReporter();`);
  } else {
    l.push(`  const licenseReporter = new NoopLicenseReporter();`);
  }
  l.push('');
  l.push(`  // Adapts cs.openCase to the small case-opener shapes refund.onExternalRefund/execute expect,`);
  l.push(`  // so refund/execute stay decoupled from importing boilpayment-cs directly (EC:D8/D12).`);
  l.push(`  const caseOpener = {`);
  l.push(`    async openReconcileMismatchCase(input: { customerId: string; referenceId: string; reason: string }) {`);
  l.push(`      await openCase({ customerId: input.customerId, kind: 'reconcile_mismatch', referenceId: input.referenceId, policy, repo: full.repo, clock: full.clock, ids: full.ids });`);
  l.push(`    },`);
  l.push(`    async openRefundFailedCase(input: { customerId: string; referenceId: string; reason: string }) {`);
  l.push(`      await openCase({ customerId: input.customerId, kind: 'refund_failed', referenceId: input.referenceId, policy, repo: full.repo, clock: full.clock, ids: full.ids });`);
  l.push(`    },`);
  l.push(`  };`);
  l.push('');

  l.push(`  const handlers = defaultHandlers({`);
  l.push(`    policy, ledger: full.ledger, repo: full.repo, notifier, clock: full.clock, ids: full.ids,`);
  if (hasSubscription) {
    l.push(`    lifecycle: { onRenewalPaid, dunning: { onPaymentFailed: dunning.onPaymentFailed } },`);
  } else {
    l.push(`    lifecycle: null,`);
  }
  if (hasCredits) {
    l.push(`    credits: { topup: (input) => applyPurchasedGrant({ customerId: input.customerId, paymentId: input.payment.id, ...supportDeps, grants: { topup, grantForPeriod } }) },
    resolveTopupCredits: (payment) => resolveTopupCredits({ payment, repo: full.repo }),`);
  } else {
    l.push(`    credits: null,`);
  }
  l.push(`    refund: { onExternalRefund: async (input: { event: Parameters<typeof onExternalRefund>[0]['event']; ledger: typeof full.ledger; repo: typeof full.repo }) => {`);
  l.push(`      const result = await onExternalRefund({ event: input.event, ledger: input.ledger, repo: input.repo, clock: full.clock, ids: full.ids, cs: caseOpener });`);
  l.push(`      await finishRefundCases({ repo: full.repo, clock: full.clock, notifier, reporter: licenseReporter });`);
  l.push(`      return result;`);
  l.push(`    } },`);
  l.push(`    cs: { dispute: (input: Omit<Parameters<typeof dispute>[0], 'clock' | 'ids' | 'reporter'>) => dispute({ ...input, clock: full.clock, ids: full.ids, reporter: licenseReporter }) },`);
  l.push(`  });`);
  l.push('');

  l.push(`  /** Capture the configured sale before redirecting to the provider. */`);
  l.push(`  const checkout = (input: Pick<Parameters<typeof startCheckout>[0], 'customerId' | 'planId' | 'provider' | 'currency' | 'requestId' | 'successUrl' | 'cancelUrl'>) => startCheckout({ ...input, ...supportDeps });`);
  l.push(`  const registerCompletedCheckout = (input: Pick<Parameters<typeof registerCheckout>[0], 'customerId' | 'checkoutId' | 'paymentRef' | 'subscriptionRef'>) => registerCheckout({ ...input, ...supportDeps });`);
  if (hasSubscription) {
    l.push(`  /** EC:A1 A2 A8 J1-J5 — mid-cycle plan upgrade (immediate proration or scheduled next-period, per policy). Resolves \`provider\` from \`sub.provider\` unless overridden. */`);
    l.push(`  async function upgrade(input: Omit<Parameters<typeof lifecycleUpgrade>[0], 'policy' | 'ledger' | 'repo' | 'clock' | 'ids' | 'provider'> & { provider?: PaymentProvider }) {`);
    l.push(`    const provider = input.provider ?? providers[input.sub.provider];`);
    l.push(`    if (!provider) throw new Error(\`provider not configured: \${input.sub.provider}\`);`);
    l.push(`    return lifecycleUpgrade({ ...input, provider, policy, ledger: full.ledger, repo: full.repo, clock: full.clock, ids: full.ids });`);
    l.push(`  }`);
    l.push('');
    l.push(`  /** EC:A3 A4 J1-J5 — downgrade, optionally clawing back the credit surplus immediately (per policy). */`);
    l.push(`  async function downgrade(input: Omit<Parameters<typeof lifecycleDowngrade>[0], 'policy' | 'ledger' | 'repo' | 'clock' | 'ids' | 'provider'> & { provider?: PaymentProvider }) {`);
    l.push(`    const provider = input.provider ?? providers[input.sub.provider];`);
    l.push(`    if (!provider) throw new Error(\`provider not configured: \${input.sub.provider}\`);`);
    l.push(`    return lifecycleDowngrade({ ...input, provider, policy, ledger: full.ledger, repo: full.repo, clock: full.clock, ids: full.ids });`);
    l.push(`  }`);
    l.push('');
    l.push(`  /** EC:A5 A6 A10 I4 J1-J5 — cancel now or at period end; resolves outstanding credits per policy. */`);
    l.push(`  async function cancel(input: Omit<Parameters<typeof lifecycleCancel>[0], 'policy' | 'ledger' | 'repo' | 'clock' | 'provider'> & { provider?: PaymentProvider }) {`);
    l.push(`    const provider = input.provider ?? providers[input.sub.provider];`);
    l.push(`    if (!provider) throw new Error(\`provider not configured: \${input.sub.provider}\`);`);
    l.push(`    return lifecycleCancel({ ...input, provider, policy, ledger: full.ledger, repo: full.repo, clock: full.clock });`);
    l.push(`  }`);
    l.push('');
    l.push(`  /** EC:A23 — undo an EC:A5 end-of-period cancel while the subscription is still active (the mirror image of cancel's credit revoke). */`);
    l.push(`  async function reactivate(input: Omit<Parameters<typeof lifecycleReactivate>[0], 'policy' | 'ledger' | 'repo' | 'clock' | 'provider'> & { provider?: PaymentProvider }) {`);
    l.push(`    const provider = input.provider ?? providers[input.sub.provider];`);
    l.push(`    if (!provider) throw new Error(\`provider not configured: \${input.sub.provider}\`);`);
    l.push(`    return lifecycleReactivate({ ...input, provider, policy, ledger: full.ledger, repo: full.repo, clock: full.clock });`);
    l.push(`  }`);
    l.push('');
  }
  if (hasCredits) {
    l.push(`  /** EC:B3 B4 B5 B14 — atomic consume against the ledger. */`);
    l.push(`  async function consume(input: Omit<Parameters<typeof consumeCredits>[0], 'policy' | 'ledger' | 'clock'>) {`);
    l.push(`    return consumeCredits({ ...input, policy, ledger: full.ledger, clock: full.clock });`);
    l.push(`  }`);
  } else {
    l.push(`  async function consume(): Promise<never> {`);
    l.push(`    throw new Error('credits not selected in paykit.config.json (goods)');`);
    l.push(`  }`);
  }
  l.push('');
  if (hasUsage) {
    l.push(`  /** EC:C2 C3 — usage event ingestion + EC:C1 C5 C6 quota/overage check. */`);
    l.push(`  async function record(input: Omit<Parameters<typeof recordUsage>[0], 'policy' | 'repo' | 'clock' | 'ids' | 'provider' | 'plan'>) {`);
    l.push(`    return recordUsage({ ...input, provider: providers[input.sub.provider], plan: await full.repo.plans.get(input.sub.planId), policy, repo: full.repo, clock: full.clock, ids: full.ids });`);
    l.push(`  }`);
    l.push(`  async function checkQuota(input: Omit<Parameters<typeof checkUsage>[0], 'policy' | 'repo' | 'ledger' | 'clock'>) {`);
    l.push(`    return checkUsage({ ...input, policy, repo: full.repo, ledger: full.ledger, clock: full.clock });`);
    l.push(`  }`);
  }
  l.push('');
  if (hasReservations) {
    l.push(`  /** EC:C10 — budget for long-running work: reserve before it starts, commit what it used on success, release on failure. */`);
    l.push(`  const reservations = {`);
    l.push(`    reserve: (input: { customerId: string; jobId: string; amount: number }) => reserveBudget({ ...input, policy, ledger: full.ledger, clock: full.clock }),`);
    l.push(`    commit: (input: { customerId: string; jobId: string; amount: number }) => commitReservation({ ...input, policy, ledger: full.ledger, clock: full.clock }),`);
    l.push(`    release: (input: { customerId: string; jobId: string }) => releaseReservation({ ...input, policy, ledger: full.ledger, clock: full.clock }),`);
    l.push(`    list: (customerId: string) => listReservations({ customerId, ledger: full.ledger }),`);
    l.push(`  };`);
    l.push('');
  }
  if (hasReports) {
    l.push(`  /** EC:I10 — read-only totals for [from, to): payments, succeeded refunds, net per currency, credit movements. */`);
    l.push(`  const reports = { settlement: (input: { from: Date; to: Date }) => settlementReport({ ...input, repo: full.repo, ledger: full.ledger }) };`);
    l.push('');
  }
  l.push(`  /** EC:D* — policy-driven refund evaluation + execution. */`);
  l.push(`  async function refund(input: Omit<Parameters<typeof evaluateRefund>[0], 'policy' | 'ledger' | 'repo' | 'clock'>, extra?: Record<string, unknown>) {`);
  l.push(`    const decision = await evaluateRefund({ ...input, policy, ledger: full.ledger, repo: full.repo, clock: full.clock });`);
  l.push(`    return {`);
  l.push(`      decision,`);
  l.push(`      // caller resolves the provider (payment.provider) and passes it in — refund/execute stays provider-agnostic.`);
  l.push(`      execute: (provider: PaymentProvider) => executeRefund({ decision, provider, ledger: full.ledger, repo: full.repo, clock: full.clock, ids: full.ids, extra, cs: caseOpener }),`);
  l.push(`    };`);
  l.push(`  }`);
  l.push('');
  l.push(`  /**`);
  l.push(`   * EC:E3 E4 E5 E13 — webhook receipt is provider-scoped. Route \`${config.infra.webhookPath}/:provider\``);
  l.push(`   * to this (see ./webhook.ts for framework snippets), or pass { provider } explicitly when only`);
  l.push(`   * one provider is configured.`);
  l.push(`   */`);
  l.push(`  async function handleWebhook(rawBody: string, headers: Record<string, string>, opts?: { provider?: ProviderName }) {`);
  l.push(`    const configured = Object.keys(providers) as ProviderName[];`);
  l.push(`    const providerName = opts?.provider ?? (configured.length === 1 ? configured[0] : undefined);`);
  l.push(`    if (!providerName) throw new Error('multiple providers configured — pass { provider } to handleWebhook');`);
  l.push(`    const provider = providers[providerName];`);
  l.push(`    if (!provider) throw new Error(\`provider not configured: \${providerName}\`);`);
  l.push(`    const received = await receiveWebhook({ provider, headers, rawBody, repo: full.repo, clock: full.clock });`);
  l.push(`    if (received.status === 200 && received.eventId) await processWebhook({ eventId: received.eventId, providers, handlers, repo: full.repo, clock: full.clock });`);
  l.push(`    return received;`);
  l.push(`  }`);
  l.push('');

  l.push(supportTs(hasCredits, hasReasonRules(config)));
  l.push(`  const cron = {`);
  if (hasCredits) {
    l.push(`    /** credits.expireDue is per-customer (see NAMING ASSUMPTION note at the top of this file) — sweep all customers. */`);
    l.push(`    expireDue: async () => {`);
    l.push(`      const customers = await full.repo.customers.list();`);
    l.push(`      for (const customer of customers) await expireDue({ ledger: full.ledger, clock: full.clock, customerId: customer.id });`);
    l.push(`    },`);
  } else {
    l.push(`    expireDue: async () => {},`);
  }
  if (hasSubscription) {
    l.push(`    dunningSweep: async () => {`);
    l.push(`      // No cast here on purpose: this object's keys become SQL column names in
      // PostgresRepo.list, so a typo must fail the typecheck, not the query.
      const due = await full.repo.subscriptions.list({ status: 'past_due' });`);
    l.push(`      const now = full.clock.now();`);
    l.push(`      for (const stale of due) {`);
    l.push(`        // EC:K1 — the list read and the write inside onGraceExpired are far apart; another`);
    l.push(`        // writer (webhook, scheduler) can bump the row in between. Re-read per attempt.`);
    l.push(`        await retryOnVersionConflict(async () => {`);
    l.push(`          const sub = await full.repo.subscriptions.get(stale.id);`);
    l.push(`          if (!sub) return;`);
    l.push(`          if (sub.graceUntil && sub.graceUntil <= now) await dunning.onGraceExpired({ sub, policy, ledger: full.ledger, repo: full.repo, notifier, clock: full.clock });`);
    l.push(`        });`);
    l.push(`      }`);
    l.push(`    },`);
  } else {
    l.push(`    dunningSweep: async () => {},`);
  }
  if (hasUsage) {
    l.push(`    closePeriods: () => settleDuePeriods({ policy, repo: full.repo, ledger: full.ledger, providers, clock: full.clock }),`);
    l.push(`    flushOutbox: () => flushOutbox({ repo: full.repo, providers, clock: full.clock }),`);
  } else {
    l.push(`    closePeriods: async () => {},`);
    l.push(`    flushOutbox: async () => {},`);
  }
  if (hasSelfScheduler) {
    l.push(`    schedulerTick: async () => {`);
    l.push(`      // self-scheduling providers: ${selfSchedulingProviders.join(', ')} (Toss is always self; Portone follows infra.scheduler).`);
    l.push(`      const selfSchedulingProviders: ProviderName[] = [${selfSchedulingProviders.map((p) => `'${p}'`).join(', ')}];`);
    l.push(`      const charged: Subscription[] = [];`);
    l.push(`      const failed: Subscription[] = [];`);
    l.push(`      for (const name of selfSchedulingProviders) {`);
    l.push(`        const provider = providers[name];`);
    l.push(`        if (!provider) continue;`);
    l.push(`        const result = await scheduler.tick({ provider, repo: full.repo, policy, ledger: full.ledger, clock: full.clock, ids: full.ids, notifier });`);
    l.push(`        charged.push(...result.charged);`);
    l.push(`        failed.push(...result.failed);`);
    l.push(`      }`);
    l.push(`      return { charged, failed };`);
    l.push(`    },`);
  } else {
    l.push(`    schedulerTick: async () => ({ charged: [] as Subscription[], failed: [] as Subscription[] }),`);
  }
  if (hasReservations) l.push(`    sweepReservations: () => sweepReservations({ repo: full.repo, ledger: full.ledger, clock: full.clock }),`);
  l.push(`    reconcile: (since: Date) => ${hasCredits ? 'recoverMissingGrants({ ...supportDeps, grants: { topup, grantForPeriod }, since })' : 'Promise.resolve([])'},`);
  l.push(`  };`);
  l.push('');
  l.push(`  // licenseReporter is available for separately composed metered CS workflows.`);
  l.push(`  // Call this at boot, before serving traffic: it fails loudly when the database is behind`);
  l.push(`  // this build instead of letting the first query die on a missing column in production.`);
  l.push(`  const verifyDbSchema = () => verifySchema({ connectionString: deps.env.DATABASE_URL, modules: ${JSON.stringify(migrationModules(config))} });`);
  l.push(`  async function initialize(opts: { verifySchema?: boolean } = {}) {`);
  l.push(`    if (opts.verifySchema !== false) await verifyDbSchema();`);
  l.push(`    for (const plan of config.plans) {`);
  l.push(`      const interval = plan.interval;`);
  l.push(`      if (interval !== null && interval !== 'month' && interval !== 'year') throw new Error('invalid plan interval');`);
  l.push(`      await full.repo.plans.put({ ...plan, interval });`);
  l.push(`    }`);
  l.push(`  }`);
  l.push('');
  l.push(`  return { handleWebhook, consume${hasUsage ? ', record, checkQuota' : ''}, checkout${hasSubscription ? ', upgrade, downgrade, cancel, reactivate' : ''}, registerCompletedCheckout, initialize, refund, support${hasReservations ? ', reservations' : ''}${hasReports ? ', reports' : ''}, cron, verifySchema: verifyDbSchema, deps: full, licenseReporter };`);
  l.push(`}`);
  l.push('');

  return l.join('\n');
}
