// webhook.ts / webhook.py generators — framework-agnostic handler + framework snippets in
// comments. EC:E13 requires the RAW body (signature verification breaks on parsed JSON).
// EC:A68 — the snippets are run by a test (apps/cli/test/webhook-snippets.test.ts): the Python ones
// read the result's attributes (it is a dataclass) and answer with the status the kit decided.
import type { PaykitConfig } from '../config.js';

export function generateWebhookTs(config: PaykitConfig): string {
  const providers = config.providers;
  const single = providers.length === 1;
  const toss = providers.includes('toss');
  const tsOpts = (provider: string, address: string) => {
    const parts = [single ? '' : `provider: ${provider}`, toss ? `remoteAddress: ${address}` : ''].filter(Boolean);
    return parts.length ? `, { ${parts.join(', ')} }` : '';
  };
  return `// Generated by \`boilpayment init\`. Framework-agnostic webhook entry — read the RAW body,
// then call handleWebhook from ./index.js. Never JSON.parse before this, or provider
// signature verification will fail (EC:E4).
${toss ? `//
// Toss signs nothing: its webhooks are accepted only from its published addresses (EC:E18), so
// handleWebhook needs the connecting socket's address (never a header a client can set). Next.js
// route handlers do not expose the socket: receive Toss webhooks with Express (below) or another
// server that does.
` : ''}//
// --- Next.js (app router) --- paykit/webhook.ts used from app${config.infra.webhookPath}${single ? '' : '/[provider]'}/route.ts:
//
//   import { createPaymentKit } from '../../../paykit/index.js';
//   export async function POST(req: Request${single ? '' : ', { params }: { params: { provider: string } }'}) {
//     const rawBody = await req.text(); // RAW, not req.json()
//     const headers = Object.fromEntries(req.headers);
//     const kit = createPaymentKit(config, deps);
//     const result = await kit.handleWebhook(rawBody, headers${single ? '' : ', { provider: params.provider as never }'});
//     return new Response(null, { status: result.status });
//   }
//
// --- Express --- mount with a RAW body parser, not express.json():
//
//   app.post('${config.infra.webhookPath}${single ? '' : '/:provider'}', express.raw({ type: '*/*' }), async (req, res) => {
//     const rawBody = req.body.toString('utf8');
//     const kit = createPaymentKit(config, deps);
//     const result = await kit.handleWebhook(rawBody, req.headers as Record<string, string>${tsOpts('req.params.provider as never', 'req.socket.remoteAddress')});
//     res.status(result.status).end();
//   });
//
// --- FastAPI --- see ./webhook.py for the Python equivalent.

export { createPaymentKit } from './index.js';
`;
}

export function generateWebhookPy(config: PaykitConfig): string {
  const providers = config.providers;
  const single = providers.length === 1;
  const toss = providers.includes('toss');
  const pyArgs = (provider: string, address: string) =>
    `${single ? '' : `, provider=${provider}`}${toss ? `, remote_address=${address}` : ''}`;
  return `"""Generated by \`boilpayment init\`. Framework-agnostic webhook entry — read the RAW body,
then call handle_webhook from ./index.py. Never parse JSON before this, or provider
signature verification will fail (EC:E4). handle_webhook returns a ReceiveResult: answer with
its .status (a dataclass attribute, not a dict key).
${toss ? `
Toss signs nothing: its webhooks are accepted only from its published addresses (EC:E18), so
handle_webhook needs the connecting socket's address (request.client.host in FastAPI,
request.META["REMOTE_ADDR"] in Django), never a header a client can set.
` : ''}
--- FastAPI ---

    from fastapi import FastAPI, Request, Response
    from .index import create_payment_kit

    app = FastAPI()
    kit = create_payment_kit(config, deps, env)

    @app.post("${config.infra.webhookPath}${single ? '' : '/{provider}'}")
    async def paykit_webhook(request: Request${single ? '' : ', provider: str'}):
        raw_body = (await request.body()).decode("utf-8")  # RAW, not request.json()
        result = await kit["handle_webhook"](raw_body, dict(request.headers)${pyArgs('provider', 'request.client.host if request.client else None')})
        return Response(status_code=result.status)

--- Django ---

    @csrf_exempt
    def paykit_webhook(request${single ? '' : ', provider'}):
        raw_body = request.body.decode("utf-8")  # RAW, not request.POST
        result = async_to_sync(kit["handle_webhook"])(raw_body, dict(request.headers)${pyArgs('provider', 'request.META.get("REMOTE_ADDR")')})
        return HttpResponse(status=result.status)

--- Next.js --- see ./webhook.ts for the TypeScript equivalent.
"""

from .index import create_payment_kit  # noqa: F401
`;
}
