// webhook.ts / webhook.py generators — framework-agnostic handler + framework snippets in
// comments. EC:E13 requires the RAW body (signature verification breaks on parsed JSON).
import type { PaykitConfig } from '../config.js';

export function generateWebhookTs(config: PaykitConfig): string {
  const providers = config.providers;
  const single = providers.length === 1;
  return `// Generated by \`boilpayment init\`. Framework-agnostic webhook entry — read the RAW body,
// then call handleWebhook from ./index.js. Never JSON.parse before this, or provider
// signature verification will fail (EC:E4).
//
// --- Next.js (app router) --- paykit/webhook.ts used from app${config.infra.webhookPath}${single ? '' : '/[provider]'}/route.ts:
//
//   import { createPaymentKit } from '../../../paykit/index.js';
//   export async function POST(req: Request${single ? '' : ', { params }: { params: { provider: string } }'}) {
//     const rawBody = await req.text(); // RAW, not req.json()
//     const headers = Object.fromEntries(req.headers);
//     const kit = createPaymentKit(config, deps);
//     const result = await kit.handleWebhook(rawBody, headers${single ? '' : ', { provider: params.provider as never }'});
//     return new Response(null, { status: result.status });
//   }
//
// --- Express --- mount with a RAW body parser, not express.json():
//
//   app.post('${config.infra.webhookPath}${single ? '' : '/:provider'}', express.raw({ type: '*/*' }), async (req, res) => {
//     const rawBody = req.body.toString('utf8');
//     const kit = createPaymentKit(config, deps);
//     const result = await kit.handleWebhook(rawBody, req.headers as Record<string, string>${single ? '' : ", { provider: req.params.provider as never }"});
//     res.status(result.status).end();
//   });
//
// --- FastAPI --- see ./webhook.py for the Python equivalent.

export { createPaymentKit } from './index.js';
`;
}

export function generateWebhookPy(config: PaykitConfig): string {
  const providers = config.providers;
  const single = providers.length === 1;
  return `"""Generated by \`boilpayment init\`. Framework-agnostic webhook entry — read the RAW body,
then call handle_webhook from ./index.py. Never parse JSON before this, or provider
signature verification will fail (EC:E4).

--- FastAPI ---

    from fastapi import FastAPI, Request
    from .index import create_payment_kit

    app = FastAPI()
    kit = create_payment_kit(config, deps, env)

    @app.post("${config.infra.webhookPath}${single ? '' : '/{provider}'}")
    async def paykit_webhook(request: Request${single ? '' : ', provider: str'}):
        raw_body = (await request.body()).decode("utf-8")  # RAW, not request.json()
        result = await kit["handle_webhook"](raw_body, dict(request.headers)${single ? '' : ', provider'})
        return {}, result["status"]

--- Django ---

    @csrf_exempt
    def paykit_webhook(request${single ? '' : ', provider'}):
        raw_body = request.body.decode("utf-8")  # RAW, not request.POST
        result = async_to_sync(kit["handle_webhook"])(raw_body, dict(request.headers)${single ? '' : ', provider'})
        return HttpResponse(status=result["status"])

--- Next.js --- see ./webhook.ts for the TypeScript equivalent.
"""

from .index import create_payment_kit  # noqa: F401
`;
}
